/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication8;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Home
 */
public class ChangeUname extends javax.swing.JFrame {

    /**
     * Creates new form ChangeUname
     */
    public ChangeUname() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        newuname = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        newpass1 = new javax.swing.JPasswordField();
        newpass2 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setFocusableWindowState(false);
        setMinimumSize(new java.awt.Dimension(540, 435));
        setName("Change Username and Password"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                formComponentHidden(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel2.setText("New Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 41, 107, 20);

        jLabel3.setText("New Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 94, 103, 20);

        jLabel4.setText("Confirm Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 143, 129, 20);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(392, 227, 110, 29);

        newuname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newunameActionPerformed(evt);
            }
        });
        getContentPane().add(newuname);
        newuname.setBounds(250, 40, 193, 26);

        jButton1.setText("Change Credentials");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 227, 169, 29);

        jButton2.setText("clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(250, 227, 110, 29);
        getContentPane().add(newpass1);
        newpass1.setBounds(250, 90, 193, 26);
        getContentPane().add(newpass2);
        newpass2.setBounds(250, 140, 193, 26);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 11, 0, 0);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication8/light-background-design-website-9.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(-1, -3, 570, 380);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String new_uname = newuname.getText();
        String new_pass1 = new String (newpass1.getPassword());
        
        String new_pass2 =new String( newpass2.getPassword());
        
        if(new_uname.length()>0 && new_pass1.length()>0 && new_pass2.length()>0)
        { try{
                if(new_pass1.equals(new_pass2)){ 
                    
                
                Class.forName("java.sql.DriverManager" ); //database connectivity
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/Students","root","1234");
                Statement stmt=con.createStatement();
                
                int i = stmt.executeUpdate("UPDATE login SET Userid = '"+ new_uname +"' , Password = '"+ new_pass1 + "' where Userid = '"+UnameAuthentication.old_uname+"'");
                //int a=stmt.executeUpdate("rename table "+UnameAuthentication.old_uname+" to "+ new_uname +";");
                
                        
                    
                    if(i>0){
                    JOptionPane.showMessageDialog(jButton1, "Username and Passord changed Successful, Please Login Again With your New Account Details");
                    new Login().setVisible(true);}
                    else
                        JOptionPane.showMessageDialog(jButton1, "Username and password change Unsuccessful");
                stmt.close();
                con.close();
                    
                     }
                else
                    JOptionPane.showMessageDialog(jButton1, "Passwords Do not match");
                
                
   
                
                
                
                
              
        }catch(Exception e)
        {JOptionPane.showMessageDialog(jButton1, e);
       }
        
        
        
        }
        else
            jLabel1.setText("Please enter Username and password");
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentHidden

    private void newunameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newunameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newunameActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       newuname.setText(null);
       newpass1.setText(null);
       newpass2.setText(null);
       
    }//GEN-LAST:event_jButton2ActionPerformed
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 ChangeUname uname = new ChangeUname();
                 uname.setVisible(true);
                 
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField newpass1;
    private javax.swing.JPasswordField newpass2;
    private javax.swing.JTextField newuname;
    // End of variables declaration//GEN-END:variables
}
