/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication8;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ma
 */
public class HomePage extends javax.swing.JPanel {
private ApplicationController applicationController;
private int period;
public static String Classname;
    /**
     * Creates new form HomePage
     */
    public HomePage(ApplicationController applicationController) {
    this.applicationController=applicationController;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    void clearAll(){
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        jCheckBox9.setSelected(false);
        jCheckBox10.setSelected(false);
        jCheckBox11.setSelected(false);
        jCheckBox12.setSelected(false);
        jCheckBox13.setSelected(false);
        jCheckBox14.setSelected(false);
        jCheckBox15.setSelected(false);
        jCheckBox16.setSelected(false);
        jCheckBox17.setSelected(false);
        jCheckBox18.setSelected(false);
        jCheckBox19.setSelected(false);
        jCheckBox20.setSelected(false);
        
    
    
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Roll No", "Name"
            }
        ));
        jTable1.setIntercellSpacing(new java.awt.Dimension(5, 5));
        jTable1.setRowHeight(30);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 50, 290, 630);

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        add(jCheckBox1);
        jCheckBox1.setBounds(330, 80, 29, 29);
        add(jCheckBox2);
        jCheckBox2.setBounds(330, 110, 29, 29);
        add(jCheckBox3);
        jCheckBox3.setBounds(330, 140, 30, 29);
        add(jCheckBox4);
        jCheckBox4.setBounds(330, 170, 30, 29);
        add(jCheckBox5);
        jCheckBox5.setBounds(330, 200, 30, 29);
        add(jCheckBox6);
        jCheckBox6.setBounds(330, 230, 30, 29);
        add(jCheckBox7);
        jCheckBox7.setBounds(330, 260, 30, 29);
        add(jCheckBox8);
        jCheckBox8.setBounds(330, 290, 30, 29);
        add(jCheckBox9);
        jCheckBox9.setBounds(330, 320, 20, 29);
        add(jCheckBox10);
        jCheckBox10.setBounds(330, 350, 29, 29);
        add(jCheckBox11);
        jCheckBox11.setBounds(330, 380, 29, 29);
        add(jCheckBox12);
        jCheckBox12.setBounds(330, 410, 29, 29);
        add(jCheckBox13);
        jCheckBox13.setBounds(330, 440, 29, 29);
        add(jCheckBox14);
        jCheckBox14.setBounds(330, 470, 29, 29);
        add(jCheckBox15);
        jCheckBox15.setBounds(330, 500, 29, 29);
        add(jCheckBox16);
        jCheckBox16.setBounds(330, 530, 29, 29);
        add(jCheckBox17);
        jCheckBox17.setBounds(330, 560, 29, 29);
        add(jCheckBox18);
        jCheckBox18.setBounds(330, 590, 29, 29);
        add(jCheckBox19);
        jCheckBox19.setBounds(330, 620, 29, 29);
        add(jCheckBox20);
        jCheckBox20.setBounds(330, 650, 29, 29);

        jButton7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButton7.setText("Update Attendance");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        add(jButton7);
        jButton7.setBounds(540, 630, 250, 29);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(640, 70, 590, 80);

        jLabel3.setText("Absent");
        add(jLabel3);
        jLabel3.setBounds(330, 50, 49, 20);

        jButton1.setText("Full Strength");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(840, 630, 140, 29);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("1.Class 12 practicals from 27th\n\n2.Physics And Chemisrty On 30th and 31st\n\n3.Biology On 1st\n\n4.Ip on 2nd and 3rd \n\n5.Teachers Are requested to Prepare Batch Timings.");
        jScrollPane2.setViewportView(jTextArea1);

        add(jScrollPane2);
        jScrollPane2.setBounds(740, 210, 540, 380);

        jLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 18)); // NOI18N
        jLabel4.setText("Notice Board");
        add(jLabel4);
        jLabel4.setBounds(750, 170, 140, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication8/light-background-design-website-9.jpg"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(-1, -3, 1350, 760);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        Object c= jTable1.getValueAt(0,1);
        System.out.print(""+c.toString());
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       
        int i=0;
        if(jCheckBox1.isSelected()==true){
            applicationController.sendAbsentData((jTable1.getValueAt(0,0).toString()),jTable1.getValueAt(0,1).toString(),period);
            i=1;
        } if(jCheckBox2.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(1,0).toString()),jTable1.getValueAt(1,1).toString(),period);
            i=1;
        } if(jCheckBox3.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(2,0).toString()),jTable1.getValueAt(2,1).toString(),period);
            i=1;
        } if(jCheckBox4.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(3,0).toString()),jTable1.getValueAt(3,1).toString(),period);
            i=1;
        } if(jCheckBox5.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(4,0).toString()),jTable1.getValueAt(4,1).toString(),period);
            i=1;
        } if(jCheckBox6.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(5,0).toString()),jTable1.getValueAt(5,1).toString(),period);
            i=1;
        } if(jCheckBox7.isSelected()==true){
            applicationController.sendAbsentData((jTable1.getValueAt(6,0).toString()),jTable1.getValueAt(6,1).toString(),period);
            i=1;
        } if(jCheckBox8.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(7,0).toString()),jTable1.getValueAt(7,1).toString(),period);
            i=1;
        } if(jCheckBox9.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(8,0).toString()),jTable1.getValueAt(8,1).toString(),period);
            i=1;
        } if(jCheckBox10.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(9,0).toString()),jTable1.getValueAt(9,1).toString(),period);
            i=1;
        } if(jCheckBox11.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(10,0).toString()),jTable1.getValueAt(10,1).toString(),period);
            i=1;
        } if(jCheckBox12.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(11,0).toString()),jTable1.getValueAt(11,1).toString(),period);
            i=1;
        } if(jCheckBox13.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(12,0).toString()),jTable1.getValueAt(12,1).toString(),period);
            i=1;
        } if(jCheckBox14.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(13,0).toString()),jTable1.getValueAt(13,1).toString(),period);
            i=1;
        } if(jCheckBox15.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(14,0).toString()),jTable1.getValueAt(14,1).toString(),period);
            i=1;
        } if(jCheckBox16.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(15,0).toString()),jTable1.getValueAt(15,1).toString(),period);
            i=1;
        } if(jCheckBox17.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(16,0).toString()),jTable1.getValueAt(16,1).toString(),period);
            i=1;
        } if(jCheckBox18.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(17,0).toString()),jTable1.getValueAt(17,1).toString(),period);
            i=1;
        } if(jCheckBox19.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(18,0).toString()),jTable1.getValueAt(18,1).toString(),period);
            i=1;
        } if(jCheckBox20.isSelected()==true){
             applicationController.sendAbsentData((jTable1.getValueAt(19,0).toString()),jTable1.getValueAt(19,1).toString(),period);
            i=1;
        }
        if(i==1){
          clearAll();
          JOptionPane.showMessageDialog(this,"The Attendance Of Class "+Classname+" Has Been Succesfully Updated");
              applicationController.showLoggedInTeacherTimetable();
        }
        else{
            JOptionPane.showMessageDialog(this,"Please Select The Students Who Are Present");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        applicationController.showLoggedInTeacherTimetable();
    }//GEN-LAST:event_jButton1ActionPerformed
 
        public void showStudentData(){
             DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.setRowCount(0);
           
       Calendar cal = Calendar.getInstance();
        cal.getTime();
        SimpleDateFormat sdf = new SimpleDateFormat("HHmm");
        String time=(sdf.format(cal.getTime()));
        int tot=Integer.parseInt(time);
        if(tot>=800&&tot<900){
            period=1;
        }else if(tot>=900&&tot<1000){
            period=2;
        }else if(tot>=1000&&tot<1100){
            period=3;
        }
        else if(tot>=1120&&tot<1220){
            period=4;
        }else if(tot>1220&&tot<=1320){
            period=5;
        }else if(tot>1320&&tot<=1420){
            period=6;
        }
        
        Date date = new Date();
        String dayOfWeek = new SimpleDateFormat("EEEE", Locale.ENGLISH).format(date);
        Classname=null;
        try{
            List<Map<String, Object>> classname = applicationController.getApplicationDao().teacherClass(period+"",applicationController.getLoggedInUsername());
            for (Map<String, Object> periodTimeTable: classname) {  
                 Classname = (String)(periodTimeTable.get(dayOfWeek)+"");
                 
            }
        }
        catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        if(  Classname == null){
            JOptionPane.showMessageDialog(null,"You Dont Have Any Class Now , You are Bieng Redirected");
            
        }else{
        try{
            List<Map<String,Object>>classdata=applicationController.getApplicationDao().studentList(Classname);
            for(Map<String, Object> classData:classdata){
                String rollno = (String)(classData.get("rollno")+"");
                String name = (String)classData.get("name");
                model.addRow(new Object[] {rollno,name});
           }
        }
         catch (Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, e.getMessage());
            
        }
        if(model.getRowCount()==0){
            JOptionPane.showMessageDialog(this,"Dear Teacher Your Are Not Having Any Class Now ....");
            applicationController.showLoggedInTeacherTimetable();
        }else{
        jLabel2.setText("Welcome "+applicationController.getLoggedInUsername()+" Your Are In Class "+Classname+" This is "+period+"th Period");
      }}
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
